import { ExportService } from '../../services/export.service';

describe('ExportService', () => {
  let exportService: ExportService;
  let mockFastify: any;

  beforeEach(() => {
    mockFastify = {
      log: {
        info: jest.fn(),
        warn: jest.fn(),
        error: jest.fn(),
        debug: jest.fn(),
      },
    };
    exportService = new ExportService(mockFastify);
  });

  describe('generateCSV', () => {
    it('should generate CSV from array of objects', () => {
      const data = [
        { name: 'Product 1', price: 100, stock: 50 },
        { name: 'Product 2', price: 200, stock: 30 },
      ];

      const csv = exportService.generateCSV(data);

      expect(csv).toContain('name');
      expect(csv).toContain('price');
      expect(csv).toContain('stock');
      expect(csv).toContain('Product 1');
      expect(csv).toContain('Product 2');
      expect(csv).toContain('100');
      expect(csv).toContain('200');
    });

    it('should generate CSV with specific fields', () => {
      const data = [
        { name: 'Product 1', price: 100, stock: 50, hidden: 'secret' },
      ];

      const csv = exportService.generateCSV(data, ['name', 'price']);

      expect(csv).toContain('name');
      expect(csv).toContain('price');
      expect(csv).not.toContain('hidden');
      expect(csv).not.toContain('secret');
    });

    it('should handle empty array', () => {
      expect(() => exportService.generateCSV([])).toThrow();
    });
  });

  describe('generatePDF', () => {
    it('should generate PDF buffer', async () => {
      const exportData = {
        title: 'Test Report',
        headers: ['Column 1', 'Column 2'],
        rows: [
          ['Value 1', 'Value 2'],
          ['Value 3', 'Value 4'],
        ],
        metadata: {
          'Generated By': 'Test',
          'Date': '2024-01-01',
        },
      };

      const pdf = await exportService.generatePDF(exportData);

      expect(pdf).toBeInstanceOf(Buffer);
      expect(pdf.length).toBeGreaterThan(0);
      // PDF files start with %PDF
      expect(pdf.toString('utf8', 0, 4)).toBe('%PDF');
    });

    it('should generate PDF without metadata', async () => {
      const exportData = {
        title: 'Simple Report',
        headers: ['Name'],
        rows: [['Test']],
      };

      const pdf = await exportService.generatePDF(exportData);

      expect(pdf).toBeInstanceOf(Buffer);
      expect(pdf.length).toBeGreaterThan(0);
    });
  });

  describe('generateSalesReportPDF', () => {
    it('should generate sales report PDF', async () => {
      const data = {
        startDate: '2024-01-01',
        endDate: '2024-01-31',
        totalSales: 10000,
        totalOrders: 50,
        avgOrderValue: 200,
        salesByZone: [
          { zone: 'KARKH', total: 6000, count: 30 },
          { zone: 'RUSAFA', total: 4000, count: 20 },
        ],
        topProducts: [
          { name: 'Product A', quantity: 100, revenue: 5000 },
          { name: 'Product B', quantity: 80, revenue: 4000 },
        ],
      };

      const pdf = await exportService.generateSalesReportPDF(data);

      expect(pdf).toBeInstanceOf(Buffer);
      expect(pdf.length).toBeGreaterThan(0);
    });
  });

  describe('generateInventoryReportPDF', () => {
    it('should generate inventory report PDF', async () => {
      const data = {
        totalProducts: 100,
        inStock: 70,
        lowStock: 20,
        outOfStock: 10,
        products: [
          { sku: 'SKU001', name: 'Product 1', stock: 50, category: 'Electronics', status: 'In Stock' },
          { sku: 'SKU002', name: 'Product 2', stock: 5, category: 'Electronics', status: 'Low Stock' },
          { sku: 'SKU003', name: 'Product 3', stock: 0, category: 'Food', status: 'Out of Stock' },
        ],
      };

      const pdf = await exportService.generateInventoryReportPDF(data);

      expect(pdf).toBeInstanceOf(Buffer);
      expect(pdf.length).toBeGreaterThan(0);
    });

    it('should handle large product list', async () => {
      const products = Array.from({ length: 50 }, (_, i) => ({
        sku: `SKU${i.toString().padStart(3, '0')}`,
        name: `Product ${i}`,
        stock: i * 10,
        category: 'Test',
        status: i === 0 ? 'Out of Stock' : 'In Stock',
      }));

      const data = {
        totalProducts: 50,
        inStock: 49,
        lowStock: 0,
        outOfStock: 1,
        products,
      };

      const pdf = await exportService.generateInventoryReportPDF(data);

      expect(pdf).toBeInstanceOf(Buffer);
      expect(pdf.length).toBeGreaterThan(0);
    });
  });
});
